SELECT      COURSE_MAIN.COURSE_ID as Subject,
            concat(USERS.LASTNAME, ', ', USERS.FIRSTNAME) AS Poster,
            concat(InReplyTo.LASTNAME, ', ', InReplyTo.FIRSTNAME) AS InReplyTo,
			USERS.PK1 AS MsgFrom,
			InReplyTo.PK1 AS MsgTo,
            COUNT(1) AS Strength
FROM   	    FORUM_MAIN INNER JOIN MSG_MAIN ON FORUM_MAIN.PK1 = MSG_MAIN.FORUMMAIN_PK1
			INNER JOIN USERS ON MSG_MAIN.USERS_PK1 = USERS.PK1
			INNER JOIN CONFERENCE_MAIN ON FORUM_MAIN.CONFMAIN_PK1 = CONFERENCE_MAIN.PK1
			INNER JOIN COURSE_MAIN ON CONFERENCE_MAIN.CRSMAIN_PK1 = COURSE_MAIN.PK1
			INNER JOIN COURSE_USERS ON COURSE_MAIN.PK1 = COURSE_USERS.CRSMAIN_PK1
			LEFT OUTER JOIN MSG_MAIN AS MsgMainReplyTo ON MSG_MAIN.MSGMAIN_PK1 = MsgMainReplyTo.PK1
			LEFT OUTER JOIN USERS AS InReplyTo ON MsgMainReplyTo.USERS_PK1 = InReplyTo.PK1
WHERE       (COURSE_MAIN.COURSE_ID LIKE '%PSY203_201760%' OR
			COURSE_MAIN.COURSE_ID LIKE '%PSY208_201760%' OR
			COURSE_MAIN.COURSE_ID LIKE '%PSY453_201760%' OR
			COURSE_MAIN.COURSE_ID LIKE '%PSY458_201760%')
AND         COURSE_USERS.USERS_PK1 = USERS.PK1
AND         COURSE_USERS.AVAILABLE_IND = 'Y'
AND         COURSE_USERS.ROW_STATUS = 0
GROUP BY    COURSE_MAIN.COURSE_ID,
            concat(USERS.LASTNAME, ', ', USERS.FIRSTNAME),
            concat(InReplyTo.LASTNAME, ', ', InReplyTo.FIRSTNAME),
			USERS.PK1,
			InReplyTo.PK1
ORDER BY    COURSE_MAIN.COURSE_ID, 
            concat(USERS.LASTNAME, ', ', USERS.FIRSTNAME),
            concat(InReplyTo.LASTNAME, ', ', InReplyTo.FIRSTNAME)
