SELECT 		COURSE_MAIN.COURSE_ID as Subject,
			SOURCE.USERS.LASTNAME + ', ' + SOURCE.USERS.FIRSTNAME AS Name,
			SOURCE.USERS.PK1 As ID,
			SOURCE.FORUM_MAIN.NAME as ForumName, REPLACE(SOURCE.MSG_MAIN.SUBJECT, 'RE: ', '') as ThreadName, 
			CASE WHEN SOURCE.MSG_MAIN.MSGMAIN_PK1 Is NULL THEN 'First Post' ELSE 'Reply' END as FirstThreadPost,
			SOURCE.MSG_MAIN.POSTED_DATE as DatePosted,
			SOURCE.MSG_MAIN.MSG_TEXT as Post,
			SOURCE.COURSE_USERS.ROLE as Role
FROM   		SOURCE.FORUM_MAIN INNER JOIN SOURCE.MSG_MAIN ON SOURCE.FORUM_MAIN.PK1 = SOURCE.MSG_MAIN.FORUMMAIN_PK1
			INNER JOIN SOURCE.USERS ON SOURCE.MSG_MAIN.USERS_PK1 = SOURCE.USERS.PK1
			INNER JOIN SOURCE.CONFERENCE_MAIN ON SOURCE.FORUM_MAIN.CONFMAIN_PK1 = SOURCE.CONFERENCE_MAIN.PK1
			INNER JOIN SOURCE.COURSE_MAIN ON SOURCE.CONFERENCE_MAIN.CRSMAIN_PK1 = SOURCE.COURSE_MAIN.PK1
			INNER JOIN SOURCE.COURSE_USERS ON SOURCE.COURSE_MAIN.PK1 = SOURCE.COURSE_USERS.CRSMAIN_PK1
WHERE  		(COURSE_MAIN.COURSE_ID LIKE '%PSY203_201860%' OR
			COURSE_MAIN.COURSE_ID LIKE '%PSY208_201860%' OR
			COURSE_MAIN.COURSE_ID LIKE '%PSY453_201860%' OR
			COURSE_MAIN.COURSE_ID LIKE '%PSY458_201860%')
AND         SOURCE.COURSE_USERS.USERS_PK1 = SOURCE.USERS.PK1
ORDER BY	COURSE_MAIN.COURSE_ID, SOURCE.FORUM_MAIN.NAME, REPLACE(SOURCE.MSG_MAIN.SUBJECT, 'RE: ', '') , CASE WHEN SOURCE.MSG_MAIN.MSGMAIN_PK1 Is NULL THEN 'First Post' ELSE 'Reply' END , SOURCE.MSG_MAIN.POSTED_DATE
