SELECT      SOURCE.COURSE_MAIN.COURSE_ID as Subject,
            SOURCE.USERS.LASTNAME + ', ' + SOURCE.USERS.FIRSTNAME AS Person,
            SOURCE.COURSE_USERS.ROLE as Role,
			SOURCE.COURSE_USERS.PK1 as ID
FROM        SOURCE.COURSE_MAIN INNER JOIN SOURCE.COURSE_USERS ON SOURCE.COURSE_MAIN.PK1 = SOURCE.COURSE_USERS.CRSMAIN_PK1
            INNER JOIN SOURCE.USERS ON SOURCE.USERS.PK1 = SOURCE.COURSE_USERS.USERS_PK1 
WHERE      (COURSE_MAIN.COURSE_ID LIKE '%PSY203_201860%' OR
			COURSE_MAIN.COURSE_ID LIKE '%PSY208_201860%' OR
			COURSE_MAIN.COURSE_ID LIKE '%PSY453_201860%' OR
			COURSE_MAIN.COURSE_ID LIKE '%PSY458_201860%')
AND         SOURCE.COURSE_USERS.AVAILABLE_IND = 'Y'
AND         SOURCE.COURSE_USERS.ROW_STATUS = 0
ORDER BY    SOURCE.COURSE_MAIN.COURSE_ID, SOURCE.COURSE_USERS.ROLE, 
            SOURCE.USERS.LASTNAME + ', ' + SOURCE.USERS.FIRSTNAME
