SELECT      COURSE_MAIN.COURSE_ID as Subject,
            SOURCE.USERS.LASTNAME + ', ' + SOURCE.USERS.FIRSTNAME AS Poster,
            InReplyTo.LASTNAME + ', ' + InReplyTo.FIRSTNAME AS InReplyTo,
			SOURCE.USERS.PK1 AS MsgFrom,
			InReplyTo.PK1 AS MsgTo,
            COUNT(1) AS Strength
FROM   	    SOURCE.FORUM_MAIN INNER JOIN SOURCE.MSG_MAIN ON SOURCE.FORUM_MAIN.PK1 = SOURCE.MSG_MAIN.FORUMMAIN_PK1
			INNER JOIN SOURCE.USERS ON SOURCE.MSG_MAIN.USERS_PK1 = SOURCE.USERS.PK1
			INNER JOIN SOURCE.CONFERENCE_MAIN ON SOURCE.FORUM_MAIN.CONFMAIN_PK1 = SOURCE.CONFERENCE_MAIN.PK1
			INNER JOIN SOURCE.COURSE_MAIN ON SOURCE.CONFERENCE_MAIN.CRSMAIN_PK1 = SOURCE.COURSE_MAIN.PK1
			INNER JOIN SOURCE.COURSE_USERS ON SOURCE.COURSE_MAIN.PK1 = SOURCE.COURSE_USERS.CRSMAIN_PK1
			LEFT OUTER JOIN SOURCE.MSG_MAIN AS MsgMainReplyTo ON SOURCE.MSG_MAIN.MSGMAIN_PK1 = MsgMainReplyTo.PK1
			LEFT OUTER JOIN SOURCE.USERS AS InReplyTo ON MsgMainReplyTo.USERS_PK1 = InReplyTo.PK1
WHERE       (COURSE_MAIN.COURSE_ID LIKE '%PSY203_201860%' OR
			COURSE_MAIN.COURSE_ID LIKE '%PSY208_201860%' OR
			COURSE_MAIN.COURSE_ID LIKE '%PSY453_201860%' OR
			COURSE_MAIN.COURSE_ID LIKE '%PSY458_201860%')
AND         SOURCE.COURSE_USERS.USERS_PK1 = SOURCE.USERS.PK1
AND         SOURCE.COURSE_USERS.AVAILABLE_IND = 'Y'
AND         SOURCE.COURSE_USERS.ROW_STATUS = 0
GROUP BY    COURSE_MAIN.COURSE_ID,
            SOURCE.USERS.LASTNAME + ', ' + SOURCE.USERS.FIRSTNAME,
            InReplyTo.LASTNAME + ', ' + InReplyTo.FIRSTNAME,
			SOURCE.USERS.PK1,
			InReplyTo.PK1
ORDER BY    COURSE_MAIN.COURSE_ID, 
            SOURCE.USERS.LASTNAME + ', ' + SOURCE.USERS.FIRSTNAME, 
            InReplyTo.LASTNAME + ', ' + InReplyTo.FIRSTNAME
