SELECT SOURCE.TERM.NAME as 'Session', 
       SOURCE.COURSE_MAIN.COURSE_ID as 'Subject Id', 
       SOURCE.COURSE_MAIN.COURSE_NAME as 'Subject Name',
       SOURCE.USERS.LASTNAME + ', ' + SOURCE.USERS.FIRSTNAME as 'Student',
	   SOURCE.USERS.PK1 as ID,
       SOURCE.GRADEBOOK_MAIN.Title as 'Column',
       SOURCE.ATTEMPT.SCORE as 'Score',
	   SOURCE.GRADEBOOK_MAIN.POSSIBLE as 'Possible',
	   SOURCE.GRADEBOOK_MAIN.WEIGHT as 'Weight',
	   SOURCE.ATTEMPT.ATTEMPT_DATE As 'Timestamp',
       SOURCE.GRADEBOOK_GRADE.MANUAL_GRADE 'Manual Grade',
       SOURCE.GRADEBOOK_GRADE.MANUAL_SCORE 'Manual Score'
FROM   SOURCE.TERM INNER JOIN SOURCE.COURSE_TERM ON SOURCE.TERM.PK1 = SOURCE.COURSE_TERM.TERM_PK1 
                   INNER JOIN SOURCE.COURSE_MAIN ON SOURCE.COURSE_TERM.CRSMAIN_PK1 = SOURCE.COURSE_MAIN.PK1
                   INNER JOIN SOURCE.COURSE_USERS ON SOURCE.COURSE_MAIN.PK1 = SOURCE.COURSE_USERS.CRSMAIN_PK1
                   INNER JOIN SOURCE.USERS ON SOURCE.COURSE_USERS.USERS_PK1 = SOURCE.USERS.PK1 
                   INNER JOIN SOURCE.GRADEBOOK_MAIN ON SOURCE.COURSE_MAIN.PK1 = SOURCE.GRADEBOOK_MAIN.CRSMAIN_PK1
                   INNER JOIN SOURCE.GRADEBOOK_GRADE ON GRADEBOOK_MAIN.PK1 = SOURCE.GRADEBOOK_GRADE.GRADEBOOK_MAIN_PK1 AND
                                                        COURSE_USERS.PK1 = SOURCE.GRADEBOOK_GRADE.COURSE_USERS_PK1
                   LEFT OUTER JOIN SOURCE.ATTEMPT ON SOURCE.GRADEBOOK_GRADE.PK1 = SOURCE.ATTEMPT.GRADEBOOK_GRADE_PK1
WHERE  SOURCE.TERM.NAME IN ('201860')
AND    SOURCE.COURSE_MAIN.AVAILABLE_IND =  'Y' 
AND    ( COURSE_MAIN.COURSE_ID LIKE '%PSY203%' OR
         COURSE_MAIN.COURSE_ID LIKE '%PSY208%' OR
         COURSE_MAIN.COURSE_ID LIKE '%PSY453%' OR
         COURSE_MAIN.COURSE_ID LIKE '%PSY458%' )
AND    SOURCE.COURSE_USERS.AVAILABLE_IND = 'Y'
AND    SOURCE.COURSE_USERS.ROW_STATUS = 0
AND    SOURCE.COURSE_USERS.ROLE = 'S'
ORDER BY 1, 4, 5, 2, 3, 6
