select		COURSE_MAIN.COURSE_ID as Subject,
			SOURCE.USERS.LASTNAME + ', ' + SOURCE.USERS.FIRSTNAME AS Name,
			SOURCE.USERS.PK1 as ID,
			Stage.ACTIVITY_ACCUMULATOR_archive.EVENT_TYPE AS Event,
			Stage.ACTIVITY_ACCUMULATOR_archive.[TIMESTAMP] AS Timestamp,
			Stage.ACTIVITY_ACCUMULATOR_archive.[DATA] AS Data,
			SOURCE.COURSE_CONTENTS.TITLE AS ContentTitle
			--Stage.ACTIVITY_ACCUMULATOR_archive.FORUM_PK1 AS Forum_PK1
from		Stage.ACTIVITY_ACCUMULATOR_archive INNER JOIN SOURCE.USERS ON Stage.ACTIVITY_ACCUMULATOR_archive.USER_PK1 = SOURCE.USERS.PK1
			INNER JOIN SOURCE.COURSE_MAIN ON Stage.ACTIVITY_ACCUMULATOR_archive.COURSE_PK1 = SOURCE.COURSE_MAIN.PK1
			INNER JOIN SOURCE.COURSE_USERS ON SOURCE.COURSE_MAIN.PK1 = SOURCE.COURSE_USERS.CRSMAIN_PK1
			INNER JOIN SOURCE.COURSE_CONTENTS ON Stage.ACTIVITY_ACCUMULATOR_archive.CONTENT_PK1 =  SOURCE.COURSE_CONTENTS.PK1
			--INNER JOIN on Forum when ready
where		(COURSE_MAIN.COURSE_ID LIKE '%PSY203_201860%' OR
			COURSE_MAIN.COURSE_ID LIKE '%PSY208_201860%' OR
			COURSE_MAIN.COURSE_ID LIKE '%PSY453_201860%' OR
			COURSE_MAIN.COURSE_ID LIKE '%PSY458_201860%')
AND         SOURCE.COURSE_USERS.USERS_PK1 = SOURCE.USERS.PK1
--order by	Name -- this added a performance hit, so is ommited. 