SELECT TERM.NAME as Session,
       COURSE_MAIN.COURSE_ID as Subject_Id,
       COURSE_MAIN.COURSE_NAME as Subject_Name,
       concat(USERS.LASTNAME, ', ', USERS.FIRSTNAME) as Student,
	   USERS.PK1 as ID,
       GRADEBOOK_MAIN.Title as Column,
       ATTEMPT.SCORE as Score,
	   GRADEBOOK_MAIN.POSSIBLE as Possible,
	   GRADEBOOK_MAIN.WEIGHT as Weight,
	   ATTEMPT.ATTEMPT_DATE As Timestamp,
       GRADEBOOK_GRADE.MANUAL_GRADE Manual_Grade,
       GRADEBOOK_GRADE.MANUAL_SCORE Manual_Score
FROM   TERM INNER JOIN COURSE_TERM ON TERM.PK1 = COURSE_TERM.TERM_PK1 
                   INNER JOIN COURSE_MAIN ON COURSE_TERM.CRSMAIN_PK1 = COURSE_MAIN.PK1
                   INNER JOIN COURSE_USERS ON COURSE_MAIN.PK1 = COURSE_USERS.CRSMAIN_PK1
                   INNER JOIN USERS ON COURSE_USERS.USERS_PK1 = USERS.PK1 
                   INNER JOIN GRADEBOOK_MAIN ON COURSE_MAIN.PK1 = GRADEBOOK_MAIN.CRSMAIN_PK1
                   INNER JOIN GRADEBOOK_GRADE ON GRADEBOOK_MAIN.PK1 = GRADEBOOK_GRADE.GRADEBOOK_MAIN_PK1 AND
                                                        COURSE_USERS.PK1 = GRADEBOOK_GRADE.COURSE_USERS_PK1
                   LEFT OUTER JOIN ATTEMPT ON GRADEBOOK_GRADE.PK1 = ATTEMPT.GRADEBOOK_GRADE_PK1
WHERE  TERM.NAME IN ('201760')
AND    COURSE_MAIN.AVAILABLE_IND =  'Y' 
AND    ( COURSE_MAIN.COURSE_ID LIKE '%PSY203%' OR
         COURSE_MAIN.COURSE_ID LIKE '%PSY208%' OR
         COURSE_MAIN.COURSE_ID LIKE '%PSY453%' OR
         COURSE_MAIN.COURSE_ID LIKE '%PSY458%' )
AND    COURSE_USERS.AVAILABLE_IND = 'Y'
AND    COURSE_USERS.ROW_STATUS = 0
AND    COURSE_USERS.ROLE = 'S'
ORDER BY 1, 4, 5, 2, 3, 6
